server:
  port: 9527

#/plat/**的请求全交到STORE-PLAT服务中去
zuul:
 ignoredServices: '*' #不能使用服务名访问
 routes:
  system:
    path: /system/**
    serviceId: SERVER-SYSTEM
  course:
    path: /courseType/**
    serviceId: SERVER-COURSE


